version: "3"
services:
  db:
    image: mongo:3.4
    volumes:
      - .mongodb:/data/db

  restaurants-api:
    build: restaurants-api/docker
    volumes:
      - ./restaurants-api:/restaurants-api
    ports:
      - 5000:5000
    depends_on:
     - db

  api-gateway:
    build: gastronomic-evaluations-api-gateway/docker
    volumes:
      - ./gastronomic-evaluations-api-gateway:/gastronomic-evaluations-api-gateway
    ports:
      - 5500:5500

  users-api:
    build: gastronomic-evaluations-users-api/docker
    volumes:
      - ./gastronomic-evaluations-users-api:/gastronomic-evaluations-users-api
    ports:
      - 5003:5003

  restaurants-front:
    build: restaurants-front/docker
    volumes:
      - ./restaurants-front:/restaurants-front
    ports:
      - 5001:5001
    depends_on:
      - restaurants-api

