version: "3"
services:
  db:
    image: mongo:3.4
    volumes:
      - .mongodb:/data/db

  restaurants-api:
    build: restaurants-api/docker
    volumes:
      - ./restaurants-api:/restaurants-api
    ports:
      - 5000:5000
    depends_on:
     - db

  landingpage:
    build: landingpage/docker
    volumes:
      - ./landingpage:/landingpage
    ports:
      - 5002:5002
    depends_on:
     - api-gateway

  api-gateway:
    build: api-gateway/docker
    volumes:
      - ./api-gateway:/api-gateway
    ports:
      - 5500:5500

  users-api:
    build: users-api/docker
    volumes:
      - ./users-api:/users-api
    ports:
      - 5003:5003
    depends_on:
      - api-gateway
      - users-db

  users-db:
    image: mongo:3.4
    volumes:
      - .users-db:/data/db

  restaurants-front:
    build: restaurants-front/docker
    volumes:
      - ./restaurants-front:/restaurants-front
    ports:
      - 5001:5001
    depends_on:
      - api-gateway

